# Generated by Django 3.2.9 on 2021-12-03 13:19

import crops.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to=crops.models.crop_image_directory)),
                ('companion', models.ManyToManyField(related_name='crops', to='crops.Crop')),
            ],
            options={
                'db_table': 'crops',
                'ordering': ['name'],
            },
        ),
    ]
