# Generated by Django 3.2.9 on 2021-12-07 15:14

import crops.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanionCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=50)),
            ],
            options={
                'db_table': 'companion_crops',
            },
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to=crops.models.crop_image_directory)),
                ('companion', models.ManyToManyField(related_name='_crops_crop_companion_+', through='crops.CompanionCrop', to='crops.Crop')),
            ],
            options={
                'db_table': 'crops',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='companioncrop',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='crop', to='crops.crop'),
        ),
        migrations.AddField(
            model_name='companioncrop',
            name='helper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='helped_by', to='crops.crop'),
        ),
        migrations.AddConstraint(
            model_name='companioncrop',
            constraint=models.UniqueConstraint(fields=('crop', 'crop'), name='unique_companion_crop'),
        ),
    ]
